language: node_js
node_js: stable

# S: Build Lifecycle
install:

#before_script:
 source ./deploy.sh

script:
  - xandeerBuild ${items}

after_script:
  - xandeerPush ${items}
# E: Build LifeCycle

branches:
  only:
    - develop

env:
 global:
    - GH_REF: github.com/xandeer/100-days-of-code.git
    - items: "portfolio"
